import '../../models/suramodel.dart';

abstract class Constants {
  List<String> arabicQuranSuraNames = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس",
  ];
  List<String> englishQuranSuraNames = [
    "Al-Fatiha",
    "Al-Baqarah",
    "Aal-E-Imran",
    "An-Nisa'",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu'minun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shu'ara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajda",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jathiya",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'a",
    "Al-Hadid",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahina",
    "As-Saff",
    "Al-Jumu'a",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddathir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba'",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Duha",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyina",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari'a",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma'un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas",
  ];
  List<String> ayatNumbers = [
    '7',
    '286',
    '200',
    '176',
    '120',
    '165',
    '206',
    '75',
    '129',
    '109',
    '123',
    '111',
    '43',
    '52',
    '99',
    '128',
    '111',
    '110',
    '98',
    '135',
    '112',
    '78',
    '118',
    '64',
    '77',
    '227',
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '5',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '6',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6',
  ];
  static final List<SuraData> allSuras = [
    SuraData(
      id: 1,
      suraNameAR: "الفاتحه",
      suraNameEn: "Al-Fatiha",
      suraNumber: 7,
    ),
    SuraData(
      id: 2,
      suraNameAR: "البقرة",
      suraNameEn: "Al-Baqarah",
      suraNumber: 286,
    ),
    SuraData(
      id: 3,
      suraNameAR: "آل عمران",
      suraNameEn: "Aal-E-Imran",
      suraNumber: 200,
    ),
    SuraData(
      id: 4,
      suraNameAR: "النساء",
      suraNameEn: "An-Nisa'",
      suraNumber: 176,
    ),
    SuraData(
      id: 5,
      suraNameAR: "المائدة",
      suraNameEn: "Al-Ma'idah",
      suraNumber: 120,
    ),
    SuraData(
      id: 6,
      suraNameAR: "الأنعام",
      suraNameEn: "Al-An'am",
      suraNumber: 165,
    ),
    SuraData(
      id: 7,
      suraNameAR: "الأعراف",
      suraNameEn: "Al-A'raf",
      suraNumber: 206,
    ),
    SuraData(
      id: 8,
      suraNameAR: "الأنفال",
      suraNameEn: "Al-Anfal",
      suraNumber: 75,
    ),
    SuraData(
      id: 9,
      suraNameAR: "التوبة",
      suraNameEn: "At-Tawbah",
      suraNumber: 129,
    ),
    SuraData(id: 10, suraNameAR: "يونس", suraNameEn: "Yunus", suraNumber: 109),
    SuraData(id: 11, suraNameAR: "هود", suraNameEn: "Hud", suraNumber: 123),
    SuraData(id: 12, suraNameAR: "يوسف", suraNameEn: "Yusuf", suraNumber: 111),
    SuraData(
      id: 13,
      suraNameAR: "الرعد",
      suraNameEn: "Ar-Ra'd",
      suraNumber: 43,
    ),
    SuraData(
      id: 14,
      suraNameAR: "إبراهيم",
      suraNameEn: "Ibrahim",
      suraNumber: 52,
    ),
    SuraData(
      id: 15,
      suraNameAR: "الحجر",
      suraNameEn: "Al-Hijr",
      suraNumber: 99,
    ),
    SuraData(
      id: 16,
      suraNameAR: "النحل",
      suraNameEn: "An-Nahl",
      suraNumber: 128,
    ),
    SuraData(
      id: 17,
      suraNameAR: "الإسراء",
      suraNameEn: "Al-Isra",
      suraNumber: 111,
    ),
    SuraData(
      id: 18,
      suraNameAR: "الكهف",
      suraNameEn: "Al-Kahf",
      suraNumber: 110,
    ),
    SuraData(id: 19, suraNameAR: "مريم", suraNameEn: "Maryam", suraNumber: 98),
    SuraData(id: 20, suraNameAR: "طه", suraNameEn: "Ta-Ha", suraNumber: 135),
    SuraData(
      id: 21,
      suraNameAR: "الأنبياء",
      suraNameEn: "Al-Anbiya",
      suraNumber: 112,
    ),
    SuraData(id: 22, suraNameAR: "الحج", suraNameEn: "Al-Hajj", suraNumber: 78),
    SuraData(
      id: 23,
      suraNameAR: "المؤمنون",
      suraNameEn: "Al-Mu'minun",
      suraNumber: 118,
    ),
    SuraData(
      id: 24,
      suraNameAR: "النّور",
      suraNameEn: "An-Nur",
      suraNumber: 64,
    ),
    SuraData(
      id: 25,
      suraNameAR: "الفرقان",
      suraNameEn: "Al-Furqan",
      suraNumber: 77,
    ),
    SuraData(
      id: 26,
      suraNameAR: "الشعراء",
      suraNameEn: "Ash-Shu'ara",
      suraNumber: 227,
    ),
    SuraData(
      id: 27,
      suraNameAR: "النّمل",
      suraNameEn: "An-Naml",
      suraNumber: 93,
    ),
    SuraData(
      id: 28,
      suraNameAR: "القصص",
      suraNameEn: "Al-Qasas",
      suraNumber: 88,
    ),
    SuraData(
      id: 29,
      suraNameAR: "العنكبوت",
      suraNameEn: "Al-Ankabut",
      suraNumber: 69,
    ),
    SuraData(
      id: 30,
      suraNameAR: "الرّوم",
      suraNameEn: "Ar-Rum",
      suraNumber: 60,
    ),
    SuraData(id: 31, suraNameAR: "لقمان", suraNameEn: "Luqman", suraNumber: 34),
    SuraData(
      id: 32,
      suraNameAR: "السجدة",
      suraNameEn: "As-Sajda",
      suraNumber: 30,
    ),
    SuraData(
      id: 33,
      suraNameAR: "الأحزاب",
      suraNameEn: "Al-Ahzab",
      suraNumber: 73,
    ),
    SuraData(id: 34, suraNameAR: "سبأ", suraNameEn: "Saba", suraNumber: 54),
    SuraData(id: 35, suraNameAR: "فاطر", suraNameEn: "Fatir", suraNumber: 45),
    SuraData(id: 36, suraNameAR: "يس", suraNameEn: "Ya-Sin", suraNumber: 83),
    SuraData(
      id: 37,
      suraNameAR: "الصافات",
      suraNameEn: "As-Saffat",
      suraNumber: 182,
    ),
    SuraData(id: 38, suraNameAR: "ص", suraNameEn: "Sad", suraNumber: 88),
    SuraData(
      id: 39,
      suraNameAR: "الزمر",
      suraNameEn: "Az-Zumar",
      suraNumber: 75,
    ),
    SuraData(id: 40, suraNameAR: "غافر", suraNameEn: "Ghafir", suraNumber: 85),
    SuraData(
      id: 41,
      suraNameAR: "فصّلت",
      suraNameEn: "Fussilat",
      suraNumber: 54,
    ),
    SuraData(
      id: 42,
      suraNameAR: "الشورى",
      suraNameEn: "Ash-Shura",
      suraNumber: 53,
    ),
    SuraData(
      id: 43,
      suraNameAR: "الزخرف",
      suraNameEn: "Az-Zukhruf",
      suraNumber: 89,
    ),
    SuraData(
      id: 44,
      suraNameAR: "الدّخان",
      suraNameEn: "Ad-Dukhan",
      suraNumber: 59,
    ),
    SuraData(
      id: 45,
      suraNameAR: "الجاثية",
      suraNameEn: "Al-Jathiya",
      suraNumber: 37,
    ),
    SuraData(
      id: 46,
      suraNameAR: "الأحقاف",
      suraNameEn: "Al-Ahqaf",
      suraNumber: 35,
    ),
    SuraData(
      id: 47,
      suraNameAR: "محمد",
      suraNameEn: "Muhammad",
      suraNumber: 38,
    ),
    SuraData(
      id: 48,
      suraNameAR: "الفتح",
      suraNameEn: "Al-Fath",
      suraNumber: 29,
    ),
    SuraData(
      id: 49,
      suraNameAR: "الحجرات",
      suraNameEn: "Al-Hujurat",
      suraNumber: 18,
    ),
    SuraData(id: 50, suraNameAR: "ق", suraNameEn: "Qaf", suraNumber: 45),
    SuraData(
      id: 51,
      suraNameAR: "الذاريات",
      suraNameEn: "Adh-Dhariyat",
      suraNumber: 60,
    ),
    SuraData(id: 52, suraNameAR: "الطور", suraNameEn: "At-Tur", suraNumber: 49),
    SuraData(
      id: 53,
      suraNameAR: "النجم",
      suraNameEn: "An-Najm",
      suraNumber: 62,
    ),
    SuraData(
      id: 54,
      suraNameAR: "القمر",
      suraNameEn: "Al-Qamar",
      suraNumber: 55,
    ),
    SuraData(
      id: 55,
      suraNameAR: "الرحمن",
      suraNameEn: "Ar-Rahman",
      suraNumber: 78,
    ),
    SuraData(
      id: 56,
      suraNameAR: "الواقعة",
      suraNameEn: "Al-Waqi'a",
      suraNumber: 96,
    ),
    SuraData(
      id: 57,
      suraNameAR: "الحديد",
      suraNameEn: "Al-Hadid",
      suraNumber: 29,
    ),
    SuraData(
      id: 58,
      suraNameAR: "المجادلة",
      suraNameEn: "Al-Mujadila",
      suraNumber: 22,
    ),
    SuraData(
      id: 59,
      suraNameAR: "الحشر",
      suraNameEn: "Al-Hashr",
      suraNumber: 24,
    ),
    SuraData(
      id: 60,
      suraNameAR: "الممتحنة",
      suraNameEn: "Al-Mumtahina",
      suraNumber: 13,
    ),
    SuraData(id: 61, suraNameAR: "الصف", suraNameEn: "As-Saff", suraNumber: 14),
    SuraData(
      id: 62,
      suraNameAR: "الجمعة",
      suraNameEn: "Al-Jumu'a",
      suraNumber: 11,
    ),
    SuraData(
      id: 63,
      suraNameAR: "المنافقون",
      suraNameEn: "Al-Munafiqun",
      suraNumber: 11,
    ),
    SuraData(
      id: 64,
      suraNameAR: "التغابن",
      suraNameEn: "At-Taghabun",
      suraNumber: 18,
    ),
    SuraData(
      id: 65,
      suraNameAR: "الطلاق",
      suraNameEn: "At-Talaq",
      suraNumber: 12,
    ),
    SuraData(
      id: 66,
      suraNameAR: "التحريم",
      suraNameEn: "At-Tahrim",
      suraNumber: 12,
    ),
    SuraData(
      id: 67,
      suraNameAR: "الملك",
      suraNameEn: "Al-Mulk",
      suraNumber: 30,
    ),
    SuraData(
      id: 68,
      suraNameAR: "القلم",
      suraNameEn: "Al-Qalam",
      suraNumber: 52,
    ),
    SuraData(
      id: 69,
      suraNameAR: "الحاقة",
      suraNameEn: "Al-Haqqah",
      suraNumber: 52,
    ),
    SuraData(
      id: 70,
      suraNameAR: "المعارج",
      suraNameEn: "Al-Ma'arij",
      suraNumber: 44,
    ),
    SuraData(id: 71, suraNameAR: "نوح", suraNameEn: "Nuh", suraNumber: 28),
    SuraData(id: 72, suraNameAR: "الجن", suraNameEn: "Al-Jinn", suraNumber: 28),
    SuraData(
      id: 73,
      suraNameAR: "المزّمّل",
      suraNameEn: "Al-Muzzammil",
      suraNumber: 20,
    ),
    SuraData(
      id: 74,
      suraNameAR: "المدّثر",
      suraNameEn: "Al-Muddathir",
      suraNumber: 56,
    ),
    SuraData(
      id: 75,
      suraNameAR: "القيامة",
      suraNameEn: "Al-Qiyamah",
      suraNumber: 40,
    ),
    SuraData(
      id: 76,
      suraNameAR: "الإنسان",
      suraNameEn: "Al-Insan",
      suraNumber: 31,
    ),
    SuraData(
      id: 77,
      suraNameAR: "المرسلات",
      suraNameEn: "Al-Mursalat",
      suraNumber: 50,
    ),
    SuraData(
      id: 78,
      suraNameAR: "النبأ",
      suraNameEn: "An-Naba'",
      suraNumber: 40,
    ),
    SuraData(
      id: 79,
      suraNameAR: "النازعات",
      suraNameEn: "An-Nazi'at",
      suraNumber: 46,
    ),
    SuraData(id: 80, suraNameAR: "عبس", suraNameEn: "Abasa", suraNumber: 42),
    SuraData(
      id: 81,
      suraNameAR: "التكوير",
      suraNameEn: "At-Takwir",
      suraNumber: 29,
    ),
    SuraData(
      id: 82,
      suraNameAR: "الإنفطار",
      suraNameEn: "Al-Infitar",
      suraNumber: 19,
    ),
    SuraData(
      id: 83,
      suraNameAR: "المطفّفين",
      suraNameEn: "Al-Mutaffifin",
      suraNumber: 36,
    ),
    SuraData(
      id: 84,
      suraNameAR: "الإنشقاق",
      suraNameEn: "Al-Inshiqaq",
      suraNumber: 25,
    ),
    SuraData(
      id: 85,
      suraNameAR: "البروج",
      suraNameEn: "Al-Buruj",
      suraNumber: 22,
    ),
    SuraData(
      id: 86,
      suraNameAR: "الطارق",
      suraNameEn: "At-Tariq",
      suraNumber: 17,
    ),
    SuraData(
      id: 87,
      suraNameAR: "الأعلى",
      suraNameEn: "Al-A'la",
      suraNumber: 19,
    ),
    SuraData(
      id: 88,
      suraNameAR: "الغاشية",
      suraNameEn: "Al-Ghashiyah",
      suraNumber: 26,
    ),
    SuraData(
      id: 89,
      suraNameAR: "الفجر",
      suraNameEn: "Al-Fajr",
      suraNumber: 30,
    ),
    SuraData(
      id: 90,
      suraNameAR: "البلد",
      suraNameEn: "Al-Balad",
      suraNumber: 20,
    ),
    SuraData(
      id: 91,
      suraNameAR: "الشمس",
      suraNameEn: "Ash-Shams",
      suraNumber: 15,
    ),
    SuraData(
      id: 92,
      suraNameAR: "الليل",
      suraNameEn: "Al-Lail",
      suraNumber: 21,
    ),
    SuraData(
      id: 93,
      suraNameAR: "الضحى",
      suraNameEn: "Ad-Duha",
      suraNumber: 11,
    ),
    SuraData(
      id: 94,
      suraNameAR: "الشرح",
      suraNameEn: "Ash-Sharh",
      suraNumber: 8,
    ),
    SuraData(id: 95, suraNameAR: "التين", suraNameEn: "At-Tin", suraNumber: 8),
    SuraData(
      id: 96,
      suraNameAR: "العلق",
      suraNameEn: "Al-Alaq",
      suraNumber: 19,
    ),
    SuraData(id: 97, suraNameAR: "القدر", suraNameEn: "Al-Qadr", suraNumber: 5),
    SuraData(
      id: 98,
      suraNameAR: "البينة",
      suraNameEn: "Al-Bayyina",
      suraNumber: 8,
    ),
    SuraData(
      id: 99,
      suraNameAR: "الزلزلة",
      suraNameEn: "Az-Zalzalah",
      suraNumber: 8,
    ),
    SuraData(
      id: 100,
      suraNameAR: "العاديات",
      suraNameEn: "Al-Adiyat",
      suraNumber: 11,
    ),
    SuraData(
      id: 101,
      suraNameAR: "القارعة",
      suraNameEn: "Al-Qari'a",
      suraNumber: 11,
    ),
    SuraData(
      id: 102,
      suraNameAR: "التكاثر",
      suraNameEn: "At-Takathur",
      suraNumber: 8,
    ),
    SuraData(id: 103, suraNameAR: "العصر", suraNameEn: "Al-Asr", suraNumber: 3),
    SuraData(
      id: 104,
      suraNameAR: "الهمزة",
      suraNameEn: "Al-Humazah",
      suraNumber: 9,
    ),
    SuraData(id: 105, suraNameAR: "الفيل", suraNameEn: "Al-Fil", suraNumber: 5),
    SuraData(id: 106, suraNameAR: "قريش", suraNameEn: "Quraysh", suraNumber: 4),
    SuraData(
      id: 107,
      suraNameAR: "الماعون",
      suraNameEn: "Al-Ma'un",
      suraNumber: 7,
    ),
    SuraData(
      id: 108,
      suraNameAR: "الكوثر",
      suraNameEn: "Al-Kawthar",
      suraNumber: 3,
    ),
    SuraData(
      id: 109,
      suraNameAR: "الكافرون",
      suraNameEn: "Al-Kafirun",
      suraNumber: 6,
    ),
    SuraData(
      id: 110,
      suraNameAR: "النصر",
      suraNameEn: "An-Nasr",
      suraNumber: 3,
    ),
    SuraData(
      id: 111,
      suraNameAR: "المسد",
      suraNameEn: "Al-Masad",
      suraNumber: 5,
    ),
    SuraData(
      id: 112,
      suraNameAR: "الإخلاص",
      suraNameEn: "Al-Ikhlas",
      suraNumber: 4,
    ),
    SuraData(
      id: 113,
      suraNameAR: "الفلق",
      suraNameEn: "Al-Falaq",
      suraNumber: 5,
    ),
    SuraData(id: 114, suraNameAR: "الناس", suraNameEn: "An-Nas", suraNumber: 6),
  ];
}
